{% set name = "powerline-status" %}
{% set version = "2.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/powerline/powerline/archive/{{ version }}.tar.gz
  sha256: 45d838dbac94a1363942899708b6ce7c71c1cad9e1b9d048affab4f630c4cb98

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - powerline
    - powerline.bindings
    - powerline.bindings.ipython
    - powerline.bindings.pdb
    - powerline.bindings.qtile
    - powerline.bindings.tmux
    - powerline.bindings.vim
    - powerline.bindings.wm
      #- powerline.bindings.zsh
    - powerline.commands
    - powerline.lib
    - powerline.lib.vcs
    - powerline.lib.watcher
    # broken in py 3.11; fixed in next release
    # - powerline.lint
    # - powerline.lint.markedjson
    - powerline.listers
    - powerline.matchers
    - powerline.matchers.vim
    - powerline.matchers.vim.plugin
    - powerline.renderers
    - powerline.renderers.ipython
    - powerline.renderers.shell
    - powerline.segments
    - powerline.segments.common
    - powerline.segments.vim
    - powerline.segments.vim.plugin
    - powerline.selectors
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://github.com/powerline/powerline
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Powerline is a statusline plugin for vim'

  description: |
    Powerline is a statusline plugin for vim, and provides statuslines and prompts for
    several other applications, including zsh, bash, fish, tmux, IPython, Awesome, i3 and Qtile.
  doc_url: https://powerline.readthedocs.io
  dev_url: https://github.com/powerline/powerline

extra:
  recipe-maintainers:
    - synapticarbors
